# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling_app', '0001_initial'),
        ('people', '0001_initial'),
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='attendance/qrcodes/')),
                ('session_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('is_open', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sheet', to='scheduling_app.scheduledsession')),
            ],
            options={
                'verbose_name': 'Feuille de Présence',
                'db_table': 'attendance_sheets',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('excuse', 'Excusé')], default='absent', max_length=10)),
                ('method', models.CharField(choices=[('qr_code', 'QR Code'), ('code_seance', 'Code de séance'), ('manuel', 'Manuel'), ('virtuel', 'Classe virtuelle')], default='manuel', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True)),
                ('justification_file', models.FileField(blank=True, null=True, upload_to='attendance/justifications/')),
                ('is_justified', models.BooleanField(default=False)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesheet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='people.student')),
            ],
            options={
                'verbose_name': 'Enregistrement de Présence',
                'db_table': 'attendance_records',
                'unique_together': {('sheet', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AbsenceSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_sessions', models.PositiveSmallIntegerField(default=0)),
                ('present_count', models.PositiveSmallIntegerField(default=0)),
                ('absent_count', models.PositiveSmallIntegerField(default=0)),
                ('justified_count', models.PositiveSmallIntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alert_sent', models.BooleanField(default=False)),
                ('course_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.coursespace')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_summaries', to='people.student')),
            ],
            options={
                'verbose_name': "Résumé d'Assiduité",
                'db_table': 'absence_summaries',
                'unique_together': {('student', 'course_space')},
            },
        ),
    ]
