# Generated by Django 4.2.30 on 2026-04-16 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencesummary',
            name='alert_level',
            field=models.CharField(choices=[('none', 'Aucune'), ('warning', 'Avertissement'), ('critical', 'Critique'), ('exclusion_risk', "Risque d'exclusion")], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='absencesummary',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absencesummary',
            name='late_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='absencesummary',
            name='punctuality_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='absencesummary',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='absencesummary',
            name='unjustified_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='justification_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='justification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('not_required', 'Non requis')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='minutes_late',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minutes de retard'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='reviewer_comment',
            field=models.TextField(blank=True),
        ),
    ]
