# Generated by Django 5.2.15 on 2026-07-11 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0003_teacher_contract_reference_teacher_hourly_rate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceCourse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                        ],
                        default="debutant",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketplace/covers/"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prix en points du portefeuille",
                        max_digits=10,
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                ("duration_hours", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours Marketplace",
                "db_table": "marketplace_courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Vidéo"),
                            ("document", "Document"),
                            ("text", "Texte"),
                            ("quiz", "Quiz"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content_url", models.URLField(blank=True)),
                ("content_text", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=10)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False,
                        help_text="Accessible gratuitement sans achat (aperçu)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="marketplace.marketplacecourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leçon",
                "db_table": "marketplace_lessons",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonCompletion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="marketplace.courselesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_lesson_completions",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complétion de Leçon",
                "db_table": "marketplace_lesson_completions",
                "unique_together": {("student", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("comment", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_reviews",
                        to="people.student",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="marketplace.marketplacecourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis",
                "db_table": "marketplace_reviews",
                "ordering": ["-created_at"],
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="CoursePurchase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_purchases",
                        to="people.student",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="marketplace.marketplacecourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achat de Cours",
                "db_table": "marketplace_purchases",
                "unique_together": {("student", "course")},
            },
        ),
    ]
