// Export des composants dashboard
export { default as DashboardPage } from './DashboardPage'
export { default as SuperAdminDashboard } from './SuperAdminDashboard'
export { default as StudentDashboard } from './StudentDashboard'
export { default as TeacherDashboard } from './TeacherDashboard'
export { default as FinancierDashboard } from './FinancierDashboard'
export { default as ScolariteDashboard } from './ScolariteDashboard'
export { default as BibliothecaireDashboard } from './BibliothecaireDashboard'
export { default as ResponsableDashboard } from './ResponsableDashboard'
export { default as SimpleDashboard } from './SimpleDashboard'
export { default as AdminDashboard } from './AdminDashboard'