# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualClassSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel_sync', 'Distanciel Synchrone'), ('hybride', 'Hybride')], default='hybride', max_length=20)),
                ('provider', models.CharField(choices=[('bbb', 'BigBlueButton'), ('jitsi', 'Jitsi Meet'), ('zoom', 'Zoom'), ('meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('autre', 'Autre')], default='bbb', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=200)),
                ('join_url', models.URLField(blank=True)),
                ('moderator_password', models.CharField(blank=True, max_length=100)),
                ('attendee_password', models.CharField(blank=True, max_length=100)),
                ('recording_url', models.URLField(blank=True)),
                ('is_recorded', models.BooleanField(default=False)),
                ('replay_available', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('room_capacity', models.PositiveSmallIntegerField(default=100)),
                ('physical_room', models.CharField(blank=True, max_length=100)),
                ('course_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_sessions', to='lms.coursespace')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de Classe Virtuelle',
                'db_table': 'virtual_class_sessions',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('moderateur', 'Modérateur'), ('presentateur', 'Présentateur'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('is_present', models.BooleanField(default=False)),
                ('join_mode', models.CharField(choices=[('online', 'En ligne'), ('physical', 'En salle')], default='online', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='virtual_class.virtualclasssession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant à la Session',
                'db_table': 'session_participants',
                'unique_together': {('session', 'user')},
            },
        ),
    ]
