# Generated by Django 5.2.15 on 2026-07-10 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0001_initial"),
        ("virtual_class", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualclasssession",
            name="scheduled_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Créneau physique correspondant (mode hybride) — permet de fusionner la présence salle + en ligne",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="virtual_class_sessions",
                to="scheduling_app.scheduledsession",
            ),
        ),
    ]
