# Generated by Django 5.2.15 on 2026-07-10 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="question_order",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "text_answer",
                    models.TextField(
                        blank=True,
                        help_text="Réponse libre (courte/longue) — correction manuelle",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True,
                        help_text="None = non corrigé automatiquement",
                        null=True,
                    ),
                ),
                (
                    "points_earned",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="lms.quizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="lms.question",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(
                        blank=True, related_name="selected_by", to="lms.questionchoice"
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse étudiant",
                "db_table": "student_answers",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
