# Generated by Django 5.2.15 on 2026-07-10 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_quizattempt_question_order_studentanswer"),
        ("people", "0003_teacher_contract_reference_teacher_hourly_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemodule",
            name="prerequisite_module",
            field=models.ForeignKey(
                blank=True,
                help_text="Module à terminer avant d'accéder à celui-ci",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlocks",
                to="lms.coursemodule",
            ),
        ),
        migrations.AddField(
            model_name="courseresource",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_versions",
                to="lms.courseresource",
            ),
        ),
        migrations.AddField(
            model_name="courseresource",
            name="version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ResourceCompletion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="lms.courseresource",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_completions",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complétion de Ressource",
                "db_table": "lms_resource_completions",
                "unique_together": {("student", "resource")},
            },
        ),
    ]
