# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('candidature_start', models.DateField(blank=True, null=True)),
                ('candidature_end', models.DateField(blank=True, null=True)),
                ('admin_enrollment_start', models.DateField(blank=True, null=True)),
                ('admin_enrollment_end', models.DateField(blank=True, null=True)),
                ('peda_enrollment_start', models.DateField(blank=True, null=True)),
                ('peda_enrollment_end', models.DateField(blank=True, null=True)),
                ('courses_start', models.DateField(blank=True, null=True)),
                ('courses_end', models.DateField(blank=True, null=True)),
                ('exams_start', models.DateField(blank=True, null=True)),
                ('exams_end', models.DateField(blank=True, null=True)),
                ('deliberation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Année Académique',
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Département / DER',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Faculté / École / Institut',
                'db_table': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='LMDRegulation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('cycle', models.CharField(choices=[('licence', 'Licence'), ('licence_pro', 'Licence Professionnelle'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('du', 'Diplôme Universitaire'), ('certificat', 'Certificat')], max_length=20)),
                ('credits_per_semester', models.PositiveSmallIntegerField(default=30)),
                ('credits_per_year', models.PositiveSmallIntegerField(default=60)),
                ('total_credits', models.PositiveSmallIntegerField(default=180)),
                ('passing_grade', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('compensation_allowed', models.BooleanField(default=True)),
                ('compensation_min_grade', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('max_years_allowed', models.PositiveSmallIntegerField(default=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Règlement LMD',
                'db_table': 'lmd_regulations',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university/')),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Université',
                'db_table': 'universities',
            },
        ),
    ]
