# Generated by Django 5.1.15 on 2026-07-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="label",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("is_current",),
                name="academic_year_single_current",
            ),
        ),
    ]
