# Generated by Django 5.2.15 on 2026-07-10 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("url", models.URLField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("grade.published", "Note publiée"),
                            ("semester_result.published", "Résultat semestriel publié"),
                            ("payment.received", "Paiement reçu"),
                            ("enrollment.validated", "Inscription validée"),
                            ("admission.decided", "Décision d'admission"),
                            ("document.generated", "Document généré"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Clé de signature HMAC-SHA256 (en-tête X-Webhook-Signature)",
                        max_length=100,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement Webhook",
                "db_table": "webhook_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.webhooksubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison Webhook",
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
            },
        ),
    ]
