# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('licence', 'Licence'), ('licence_pro', 'Licence Professionnelle'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('du', 'Diplôme Universitaire'), ('certificat', 'Certificat'), ('micro_cert', 'Micro-Certification')], max_length=20)),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride')], default='hybride', max_length=20)),
                ('duration_semesters', models.PositiveSmallIntegerField(default=6)),
                ('languages', models.CharField(default='Français', max_length=100)),
                ('prerequisites', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('preparation', 'En préparation'), ('active', 'Active'), ('suspendue', 'Suspendue'), ('archivee', 'Archivée')], default='preparation', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('candidature_open', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic.department')),
                ('regulation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.lmdregulation')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programme / Formation',
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=50)),
                ('total_credits', models.PositiveSmallIntegerField(default=30)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='programs.program')),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['number'],
                'unique_together': {('program', 'number')},
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('fondamentale', 'Fondamentale'), ('transversale', 'Transversale'), ('optionnelle', 'Optionnelle'), ('libre', 'Libre')], default='fondamentale', max_length=20)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('volume_hours', models.PositiveSmallIntegerField(default=45)),
                ('eval_mode', models.CharField(choices=[('controle_continu', 'Contrôle Continu'), ('examen_final', 'Examen Final'), ('mixte', 'Mixte CC + Examen')], default='mixte', max_length=20)),
                ('compensation_allowed', models.BooleanField(default=True)),
                ('passing_grade', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_ues', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='programs.semester')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'db_table': 'ues',
                'unique_together': {('semester', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('promotion', 'Promotion'), ('td', 'Groupe TD'), ('tp', 'Groupe TP')], default='promotion', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=30)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='programs.program')),
            ],
            options={
                'verbose_name': 'Groupe / Promotion',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('cm', 'Cours Magistral'), ('td', 'Travaux Dirigés'), ('tp', 'Travaux Pratiques'), ('projet', 'Projet'), ('stage', 'Stage'), ('seminaire', 'Séminaire'), ('atelier', 'Atelier'), ('classe_virtuelle', 'Classe Virtuelle'), ('asynchrone', 'Activité Asynchrone')], default='cm', max_length=20)),
                ('volume_hours', models.PositiveSmallIntegerField(default=15)),
                ('credits', models.PositiveSmallIntegerField(default=1)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_ecs', to=settings.AUTH_USER_MODEL)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecs', to='programs.ue')),
            ],
            options={
                'verbose_name': 'Élément Constitutif',
                'db_table': 'ecs',
                'unique_together': {('ue', 'code')},
            },
        ),
    ]
