# Generated by Django 5.1.15 on 2026-08-04 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_ref", ""), _negated=True),
                fields=("transaction_ref",),
                name="unique_nonblank_transaction_ref",
            ),
        ),
    ]
