# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('amphi', 'Amphithéâtre'), ('salle_cours', 'Salle de cours'), ('salle_td', 'Salle TD'), ('labo', 'Laboratoire'), ('salle_info', 'Salle informatique'), ('virtuelle', 'Salle virtuelle')], max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=30)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_computer', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('is_virtual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Salle',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='ScheduledSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel_sync', 'Distanciel Synchrone'), ('distanciel_async', 'Distanciel Asynchrone'), ('hybride', 'Hybride')], default='presentiel', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('reporte', 'Reporté'), ('realise', 'Réalisé')], default='planifie', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='programs.ec')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.group')),
                ('rescheduled_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling_app.scheduledsession')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling_app.room')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Séance Planifiée',
                'db_table': 'scheduled_sessions',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='programs.group')),
                ('sessions', models.ManyToManyField(blank=True, to='scheduling_app.scheduledsession')),
            ],
            options={
                'verbose_name': 'Emploi du Temps',
                'db_table': 'timetables',
            },
        ),
    ]
