# Generated by Django 5.2.15 on 2026-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(
                default=False, help_text="Double authentification (TOTP) activée"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret TOTP (base32), vide tant que non activé",
                max_length=64,
            ),
        ),
    ]
