# Generated by Django 5.2.15 on 2026-07-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_mfa_enabled_user_mfa_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("accounts", "Comptes & Rôles"),
                    ("academic", "Académique"),
                    ("programs", "Programmes"),
                    ("people", "Personnes"),
                    ("admissions", "Admissions"),
                    ("enrollment", "Inscriptions"),
                    ("finance", "Finance"),
                    ("documents", "Documents"),
                    ("evaluation", "Évaluation"),
                    ("lms", "LMS"),
                    ("virtual_class", "Classes Virtuelles"),
                    ("attendance", "Présences"),
                    ("scheduling", "Planning"),
                    ("internships", "Stages"),
                    ("communication", "Communication"),
                    ("analytics", "Analytics"),
                ],
                max_length=50,
            ),
        ),
    ]
