# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('memoire_licence', 'Mémoire de Licence'), ('memoire_master', 'Mémoire de Master'), ('these_doctorat', 'Thèse de Doctorat')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('sujet_propose', 'Sujet proposé'), ('sujet_valide', 'Sujet validé'), ('en_redaction', 'En rédaction'), ('depose', 'Déposé'), ('soutenu', 'Soutenu'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='sujet_propose', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('final_file', models.FileField(blank=True, null=True, upload_to='theses/final/')),
                ('plagiarism_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('co_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_supervised_theses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to='people.student')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_theses', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_theses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mémoire / Thèse',
                'db_table': 'theses',
            },
        ),
        migrations.CreateModel(
            name='ThesisProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='theses/progress/')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='internships.thesis')),
            ],
            options={
                'verbose_name': 'Suivi de Mémoire',
                'db_table': 'thesis_progress',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField(blank=True)),
                ('company_supervisor', models.CharField(blank=True, max_length=200)),
                ('company_supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('en_recherche', 'En recherche'), ('convention_signee', 'Convention signée'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('valide', 'Validé'), ('abandonne', 'Abandonné')], default='en_recherche', max_length=20)),
                ('convention_file', models.FileField(blank=True, null=True, upload_to='internships/conventions/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='internships/reports/')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='people.student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_internships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stage',
                'db_table': 'internships',
            },
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_date', models.DateTimeField()),
                ('room', models.CharField(blank=True, max_length=100)),
                ('virtual_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('planifiee', 'Planifiée'), ('realisee', 'Réalisée'), ('reportee', 'Reportée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, max_length=50)),
                ('pv_file', models.FileField(blank=True, null=True, upload_to='defenses/pv/')),
                ('notes', models.TextField(blank=True)),
                ('jury_members', models.ManyToManyField(blank=True, related_name='defense_jury', to=settings.AUTH_USER_MODEL)),
                ('jury_president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defense_president', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense', to='internships.thesis')),
            ],
            options={
                'verbose_name': 'Soutenance',
                'db_table': 'defenses',
            },
        ),
    ]
