# Generated by Django 5.2.15 on 2026-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="plagiarism_analysis_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="thesis",
            name="plagiarism_report_url",
            field=models.URLField(blank=True),
        ),
    ]
