# Generated by Django 5.1.15 on 2026-08-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0002_thesis_plagiarism_analysis_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="report_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thesis",
            name="progress_percentage",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="thesis",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="internship",
            name="status",
            field=models.CharField(
                choices=[
                    ("en_recherche", "En recherche"),
                    ("convention_signee", "Convention signée"),
                    ("en_cours", "En cours"),
                    ("rapport_soumis", "Rapport soumis"),
                    ("termine", "Terminé"),
                    ("valide", "Validé"),
                    ("abandonne", "Abandonné"),
                ],
                default="en_recherche",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="status",
            field=models.CharField(
                choices=[
                    ("sujet_propose", "Sujet proposé"),
                    ("sujet_valide", "Sujet validé"),
                    ("sujet_rejete", "Sujet rejeté"),
                    ("en_redaction", "En rédaction"),
                    ("depose", "Déposé"),
                    ("soutenu", "Soutenu"),
                    ("valide", "Validé"),
                    ("rejete", "Rejeté"),
                ],
                default="sujet_propose",
                max_length=20,
            ),
        ),
    ]
