# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('requires_validation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Catégorie de Document',
                'db_table': 'document_categories',
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='ged/students/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('depose', 'Déposé'), ('en_verification', 'En vérification'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('archive', 'Archivé')], default='depose', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentcategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='people.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Étudiant',
                'db_table': 'student_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('doc_type', models.CharField(choices=[('fiche_inscription', "Fiche d'inscription"), ('certificat_scolarite', 'Certificat de scolarité'), ('certificat_frequentation', 'Certificat de fréquentation'), ('attestation_reussite', 'Attestation de réussite'), ('releve_notes', 'Relevé de notes'), ('bulletin', 'Bulletin'), ('convocation', 'Convocation'), ('carte_etudiant', "Carte d'étudiant"), ('diplome', 'Diplôme'), ('attestation_fin_cycle', 'Attestation de fin de cycle'), ('pv_deliberation', 'PV de délibération')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated/%Y/%m/')),
                ('verification_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('status', models.CharField(choices=[('genere', 'Généré'), ('signe', 'Signé'), ('delivre', 'Délivré'), ('annule', 'Annulé')], default='genere', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='people.student')),
            ],
            options={
                'verbose_name': 'Document Généré',
                'db_table': 'generated_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('verification_method', models.CharField(default='qr_code', max_length=20)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.generateddocument')),
            ],
            options={
                'db_table': 'document_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
