# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('lms', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('vue_ressource', 'Vue ressource'), ('telechargement', 'Téléchargement'), ('soumission_devoir', 'Soumission devoir'), ('tentative_quiz', 'Tentative quiz'), ('participation_forum', 'Participation forum'), ('classe_virtuelle', 'Classe virtuelle'), ('vue_video', 'Vue vidéo')], max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='lms.coursespace')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.courseresource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activities', to='people.student')),
            ],
            options={
                'verbose_name': "Activité d'Apprentissage",
                'db_table': 'learning_activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('stat_type', models.CharField(choices=[('effectifs', 'Effectifs'), ('inscriptions', 'Inscriptions'), ('paiements', 'Paiements'), ('resultats', 'Résultats'), ('assiduité', 'Assiduité'), ('lms', 'Activité LMS')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
            ],
            options={
                'verbose_name': 'Statistique Dashboard',
                'db_table': 'dashboard_stats',
            },
        ),
        migrations.CreateModel(
            name='EngagementScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_count', models.PositiveIntegerField(default=0)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('resources_viewed', models.PositiveSmallIntegerField(default=0)),
                ('assignments_submitted', models.PositiveSmallIntegerField(default=0)),
                ('quizzes_attempted', models.PositiveSmallIntegerField(default=0)),
                ('forum_posts', models.PositiveSmallIntegerField(default=0)),
                ('virtual_class_attended', models.PositiveSmallIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dropout_risk', models.CharField(choices=[('faible', 'Faible risque'), ('moyen', 'Risque moyen'), ('eleve', 'Risque élevé'), ('critique', 'Risque critique')], default='faible', max_length=10)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('course_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_scores', to='lms.coursespace')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_scores', to='people.student')),
            ],
            options={
                'verbose_name': "Score d'Engagement",
                'db_table': 'engagement_scores',
                'unique_together': {('student', 'course_space', 'academic_year')},
            },
        ),
    ]
