# Generated by Django 4.2.30 on 2026-04-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementscore',
            name='days_inactive',
            field=models.PositiveSmallIntegerField(default=0, help_text="Jours d'inactivité"),
        ),
        migrations.AddField(
            model_name='engagementscore',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Date de dernière activité', null=True),
        ),
        migrations.AddField(
            model_name='engagementscore',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, help_text='Recommandations personnalisées'),
        ),
        migrations.AddField(
            model_name='engagementscore',
            name='success_prediction_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Score prédictif de réussite (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='engagementscore',
            name='success_probability',
            field=models.CharField(blank=True, help_text='Probabilité de réussite', max_length=50),
        ),
    ]
