# Generated by Django 4.2.30 on 2026-04-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_engagementscore_days_inactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementscore',
            name='avg_module_progress',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Progression moyenne sur les modules', max_digits=5),
        ),
        migrations.AddField(
            model_name='engagementscore',
            name='forum_participation_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de participation aux forums', max_digits=5),
        ),
        migrations.AddField(
            model_name='engagementscore',
            name='quiz_completion_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de quiz complétés', max_digits=5),
        ),
    ]
