# Generated by Django 5.2.15 on 2026-07-10 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics_app", "0003_engagementscore_avg_module_progress_and_more"),
        ("people", "0003_teacher_contract_reference_teacher_hourly_rate_and_more"),
        ("programs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("completion", "Complétion de cours"),
                            ("excellence", "Excellence académique"),
                            ("participation", "Participation active"),
                            ("certification", "Certification"),
                            ("skill", "Compétence validée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="badges/icons/"),
                ),
                ("criteria", models.TextField(help_text="Critères d'obtention")),
                ("points", models.PositiveSmallIntegerField(default=10)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Badge",
                "db_table": "badges",
            },
        ),
        migrations.CreateModel(
            name="MicroCertification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=300)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
                ("duration_hours", models.PositiveSmallIntegerField(default=20)),
                ("credits", models.PositiveSmallIntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_free", models.BooleanField(default=True)),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics_app.badge",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Micro-Certification",
                "db_table": "micro_certifications",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portefeuille",
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("credit", "Crédit"),
                            ("debit", "Débit"),
                            ("reward", "Récompense"),
                            ("purchase", "Achat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=300)),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="analytics_app.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Wallet",
                "db_table": "wallet_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentBadge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics_app.badge",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge Étudiant",
                "db_table": "student_badges",
                "unique_together": {("student", "badge")},
            },
        ),
        migrations.CreateModel(
            name="StudentCertification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Inscrit"),
                            ("in_progress", "En cours"),
                            ("completed", "Complété"),
                            ("certified", "Certifié"),
                            ("failed", "Échoué"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("certificate_url", models.URLField(blank=True)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics_app.microcertification",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification Étudiant",
                "db_table": "student_certifications",
                "unique_together": {("student", "certification")},
            },
        ),
    ]
