# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('grade', models.CharField(choices=[('assistant', 'Assistant'), ('maitre_assistant', 'Maître-Assistant'), ('maitre_conference', 'Maître de Conférences'), ('professeur', 'Professeur'), ('vacataire', 'Vacataire'), ('invite', 'Invité')], default='assistant', max_length=30)),
                ('status', models.CharField(choices=[('permanent', 'Permanent'), ('vacataire', 'Vacataire'), ('invite', 'Invité'), ('emerite', 'Émérite')], default='permanent', max_length=20)),
                ('specialities', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('office', models.CharField(blank=True, max_length=50)),
                ('weekly_hours_quota', models.PositiveSmallIntegerField(default=8)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academic.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(default='Ivoirienne', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('candidat', 'Candidat'), ('admis', 'Admis'), ('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('diplome', 'Diplômé'), ('abandonne', 'Abandonné'), ('exclu', 'Exclu'), ('suspendu', 'Suspendu')], default='candidat', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('baccalaureate_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baccalaureate_series', models.CharField(blank=True, max_length=20)),
                ('baccalaureate_mention', models.CharField(blank=True, max_length=50)),
                ('current_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='programs.program')),
                ('current_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.academicyear')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='AdminStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('service', models.CharField(choices=[('scolarite', 'Scolarité'), ('finance', 'Finance'), ('rh', 'Ressources Humaines'), ('informatique', 'Informatique'), ('bibliotheque', 'Bibliothèque'), ('direction', 'Direction'), ('autre', 'Autre')], max_length=30)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel Administratif',
                'db_table': 'admin_staff',
            },
        ),
    ]
