# Generated by Django 5.2.15 on 2026-07-06 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentGuardian",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("pere", "Père"),
                            ("mere", "Mère"),
                            ("tuteur_legal", "Tuteur légal"),
                            ("oncle", "Oncle"),
                            ("tante", "Tante"),
                            ("grand_parent", "Grand-parent"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone secondaire"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Côte d'Ivoire", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profession"
                    ),
                ),
                (
                    "employer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Employeur"
                    ),
                ),
                (
                    "can_receive_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Peut recevoir des notifications"
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Types de notifications autorisées",
                    ),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=False, verbose_name="Contact prioritaire"
                    ),
                ),
                (
                    "is_emergency_contact",
                    models.BooleanField(default=True, verbose_name="Contact d'urgence"),
                ),
                (
                    "has_legal_authority",
                    models.BooleanField(default=True, verbose_name="Autorité légale"),
                ),
                (
                    "id_card_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Numéro pièce d'identité",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents_guardians",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent/Tuteur",
                "verbose_name_plural": "Parents/Tuteurs",
                "db_table": "parent_guardians",
                "ordering": ["-is_primary_contact", "last_name", "first_name"],
            },
        ),
    ]
