# Generated by Django 5.2.15 on 2026-07-10 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_parentguardian"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="contract_reference",
            field=models.CharField(
                blank=True,
                help_text="Référence de contrat (vacataires/invités)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Taux horaire (vacataires/invités)",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="people.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilité Enseignant",
                "db_table": "teacher_availabilities",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
    ]
