# Generated by Django 5.2.15 on 2026-07-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_teacher_contract_reference_teacher_hourly_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentguardian",
            name="country",
            field=models.CharField(default="Mali", max_length=100, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="student",
            name="nationality",
            field=models.CharField(default="Malienne", max_length=100),
        ),
    ]
