# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('en_instruction', 'En instruction'), ('complete', 'Dossier complet'), ('incomplete', 'Dossier incomplet'), ('admis', 'Admis'), ('admis_liste_attente', "Admis (liste d'attente)"), ('refuse', 'Refusé'), ('desiste', 'Désisté'), ('converti', 'Converti en inscription')], default='brouillon', max_length=30)),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_diploma', models.CharField(blank=True, max_length=200)),
                ('last_diploma_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_institution', models.CharField(blank=True, max_length=200)),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('motivation_letter', models.TextField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('application_fee_paid', models.BooleanField(default=False)),
                ('application_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature',
                'db_table': 'applications',
                'unique_together': {('applicant', 'program', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('doc_type', models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('passeport', 'Passeport'), ('diplome', 'Diplôme'), ('releve_notes', 'Relevé de Notes'), ('lettre_motivation', 'Lettre de Motivation'), ('cv', 'Curriculum Vitae'), ('photo', "Photo d'identité"), ('autre', 'Autre')], max_length=30)),
                ('file', models.FileField(upload_to='admissions/documents/')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de vérification'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de Candidature',
                'db_table': 'application_documents',
            },
        ),
        migrations.CreateModel(
            name='AdmissionDecision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('admis_attente', "Admis liste d'attente"), ('refuse', 'Refusé')], max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('acceptance_deadline', models.DateField(blank=True, null=True)),
                ('accepted_by_student', models.BooleanField(null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='admissions.application')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Décision d'Admission",
                'db_table': 'admission_decisions',
            },
        ),
    ]
