# Generated by Django 5.2.15 on 2026-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissiondecision",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Résultat publié (consultable par le candidat)"
            ),
        ),
        migrations.AddField(
            model_name="admissiondecision",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
