# Generated by Django 4.2.30 on 2026-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('programs', '0001_initial'),
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('premiere_inscription', 'Première inscription'), ('reinscription', 'Réinscription'), ('transfert', 'Transfert')], default='premiere_inscription', max_length=30)),
                ('enrollment_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_validated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_enrollments', to='people.student')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription Administrative',
                'db_table': 'admin_enrollments',
                'unique_together': {('student', 'academic_year', 'program')},
            },
        ),
        migrations.CreateModel(
            name='PedaEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peda_enrollments', to='enrollment.adminenrollment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.group')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.semester')),
            ],
            options={
                'verbose_name': 'Inscription Pédagogique',
                'db_table': 'peda_enrollments',
                'unique_together': {('admin_enrollment', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='UEEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('prerequisite_waived', models.BooleanField(default=False)),
                ('waiver_reason', models.TextField(blank=True)),
                ('peda_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_enrollments', to='enrollment.pedaenrollment')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ue')),
            ],
            options={
                'verbose_name': 'Inscription UE',
                'db_table': 'ue_enrollments',
                'unique_together': {('peda_enrollment', 'ue')},
            },
        ),
    ]
