# Generated by Django 5.2.15 on 2026-07-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminenrollment",
            name="previous_program",
            field=models.ForeignKey(
                blank=True,
                help_text="Programme d'origine (transfert uniquement)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="programs.program",
            ),
        ),
    ]
